{"category": "Popular Streaming Movies", "movie": "Run Rabbit Run", "rating": "35%", "description": "As a fertility doctor, Sarah has a firm understanding of the cycle of life. However, when she is forced to make sense of the increasingly strange behavior of her young daughter, Sarah must challenge her own beliefs and confront a ghost from her past."}
{"category": "Popular Streaming Movies", "movie": "Knights of the Zodiac", "rating": "23%", "description": "Based on the international anime sensation, Knights of the Zodiac brings the Saint Seiya saga to the big screen in live-action for the first time. Seiya (Mackenyu), a headstrong street teen, spends his time fighting for cash while he searches for his abducted sister. When one of his fights unwittingly taps into mystical powers he never knew he had, Seiya finds himself thrust into a world of warring saints, ancient magical training and a reincarnated goddess who needs his protection. If he’s to survive, he will need to embrace his destiny and sacrifice everything to take his rightful place among the Knights of the Zodiac."}
{"category": "Popular Streaming Movies", "movie": "Evil Dead Rise", "rating": "83%", "description": "In the fifth Evil Dead film, a road-weary Beth pays an overdue visit to her older sister Ellie, who is raising three kids on her own in a cramped L.A apartment. The sisters' reunion is cut short by the discovery of a mysterious book deep in the bowels of Ellie's building, giving rise to flesh-possessing demons, and thrusting Beth into a primal battle for survival as she is faced with the most nightmarish version of motherhood imaginable."}
{"category": "Popular Streaming Movies", "movie": "Guy Ritchie's The Covenant", "rating": "84%", "description": "Guy Ritchie's The Covenant follows US Army Sergeant John Kinley (Jake Gyllenhaal) and Afghan interpreter Ahmed (Dar Salim). After an ambush, Ahmed goes to Herculean lengths to save Kinley’s life. When Kinley learns that Ahmed and his family were not given safe passage to America as promised, he must repay his debt by returning to the war zone to retrieve them before the Taliban hunts them down first."}
{"category": "Most Popular TV on RT ", "movie": "Secret Invasion", "rating": "63%", "description": "Nick Fury learns about the Skrulls and their invasion."}
{"category": "Most Popular TV on RT ", "movie": "The Idol", "rating": "22%", "description": "As Jocelyn preps for her triumphant return, a leaked photo sends her team into crisis mode just as a journalist arrives to do an in-depth profile on her; Jocelyn has a chance encounter with nightclub owner Tedros."}
{"category": "Popular Streaming Movies", "movie": "Dungeons & Dragons: Honor Among Thieves", "rating": "90%", "description": "A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people. Dungeons & Dragons: Honor Among Thieves brings the rich world and playful spirit of the legendary roleplaying game to the big screen in a hilarious and action-packed adventure."}
{"category": "Popular Streaming Movies", "movie": "Take Care of Maya", "rating": "92%", "description": "When nine-year-old Maya Kowalski was admitted to Johns Hopkins All Children's Hospital in 2016, nothing could have prepared her or her family for what they were about to go through. As the medical team tried to understand her rare illness, they began to question the basic truths that bound the Kowalskis together. Suddenly, Maya was in state custody -- despite two parents who were desperate to bring their daughter home. The story of the Kowalski family -- as told in their own words -- will change the way you look at children's healthcare forever."}
{"category": "Most Popular TV on RT ", "movie": "Hijack", "rating": "90%", "description": "Sam Nelson gets on a flight to London hoping to win back his ex-wife, but something on board feels wrong, and his suspicions are confirmed."}
{"category": "Most Popular TV on RT ", "movie": "The Bear", "rating": "100%", "description": "Faced with the reality of opening a new restaurant, the crew must make a plan."}
{"category": "Popular Streaming Movies", "movie": "Clean", "rating": "100%", "description": "Trauma cleaners clean spaces that no one else will touch -- hoarder sites, meth-labs, murder scenes, deaths and suicides. They clean the homes of some of society's most vulnerable people -- the neglected, the lonely, the addicted, and the mentally unwell. When illness forces her away from her beloved trauma cleaning business, Sandra Pankhurst faces up to her traumatic past and begins a search for her birth mother. Meanwhile, her workers approach this difficult work with camaraderie and humor, bringing hope to their clients despite carrying trauma of their own. Clean shows us that life is more fragile than we might think, but there is hope and reassurance in human connection."}
{"category": "Most Popular TV on RT ", "movie": "Suits", "rating": "90%", "description": null}
{"category": "Most Popular TV on RT ", "movie": "The Crowded Room", "rating": "31%", "description": "Danny Sullivan is arrested for a violent crime; Rya Goodwin probes his troubled past for answers."}
{"category": "New TV This Week", "movie": "The Bachelorette", "rating": "- -", "description": "Twenty-five men travel across the country searching for love and hoping to find it with bachelorette Charity Lawson."}
{"category": "New TV This Week", "movie": "Secret Chef", "rating": "- -", "description": "Ten chefs from varied culinary backgrounds awaken to a mysterious world of kitchens, conveyor belts and alias names; before knowing each other, they are paired in teams to compete for their first chance toward the goal of winning $100,000."}
{"category": "New TV This Week", "movie": "Ten-Year-Old Tom", "rating": "- -", "description": "A youngster puts up with the bad influences in his life including litigious parents, drug dealing bus drivers, and inappropriate band teachers."}
{"category": "New TV This Week", "movie": "grown-ish", "rating": "- -", "description": "The crew goes to a music festival before parting ways for the summer; after lunch with his dad, Andre suffers from \"analysis paralysis\" about choosing a major, his relationship with Annika, and his plans for the upcoming school year."}
{"category": "New TV This Week", "movie": "Cannes Confidential", "rating": "- -", "description": "Investigating the murder of a street artist, Cannes detective Camille Delmasse keeps running into the suave but shady Harry King; Camille's father, the former chief of police, is set to be cleared of corruption until secrets upend events."}
{"category": "New TV This Week", "movie": "The Gold", "rating": "86%", "description": "Six armed men steal £26m worth of gold and set about trying to dispose of the bullion."}
{"category": "Popular Streaming Movies", "movie": "Extraction 2", "rating": "79%", "description": "Chris Hemsworth returns as Tyler Rake in EXTRACTION 2, the sequel to Netflix's blockbuster action film EXTRACTION. After barely surviving the events of the first movie, Rake is back as the Australian black ops mercenary, tasked with another deadly mission: rescuing the battered family of a ruthless Georgian gangster from the prison where they are being held."}
{"category": "New TV This Week", "movie": "Tom Clancy's Jack Ryan", "rating": "83%", "description": "Up-and-coming CIA analyst Jack Ryan is thrust into a dangerous field assignment for the first time; he uncovers a pattern in terrorist communication that launches him into the middle of a dangerous gambit with a new breed of terrorism."}
{"category": "Most Popular TV on RT ", "movie": "I'm a Virgo", "rating": "95%", "description": "A coming-of-age joyride about Cootie, a 13-foot-tall man, who escapes to experience the beauty and contradictions of the real world; he forms friendships, finds love, navigates awkward situations, and encounters his idol named The Hero."}
{"category": "New TV This Week", "movie": "Warrior", "rating": "100%", "description": "Mai Ling uses her government connections to consolidate power; Ah Sahm and the Hop Wei must find new ways to survive."}
{"category": "Most Popular TV on RT ", "movie": "Platonic", "rating": "92%", "description": "After a long rift in their friendship, Sylvia reunites with her old best friend, the newly divorced Will."}
{"category": "Popular Streaming Movies", "movie": "You Hurt My Feelings", "rating": "95%", "description": "From acclaimed filmmaker Nicole Holofcener comes a sharply observed comedy about a novelist whose long standing marriage is suddenly upended when she overhears her husband give his honest reaction to her latest book. A film about trust, lies, and the things we say to the people we love most."}
{"category": "Most Popular TV on RT ", "movie": "Black Mirror", "rating": "77%", "description": "An average woman is stunned to discover a global streaming platform has launched a prestige TV drama adaptation of her life — in which she is portrayed by Hollywood A-lister Salma Hayek Pinault."}
{"category": "Most Popular TV on RT ", "movie": "Silo", "rating": "87%", "description": "Sheriff Becker's plans for the future are thrown off course after his wife meets a hacker with information about the silo."}
{"category": "Popular Streaming Movies", "movie": "Leave No Trace", "rating": "100%", "description": "A father and daughter live a perfect but mysterious existence in Forest Park, a beautiful nature reserve near Portland, Ore., rarely making contact with the world. But when a small mistake tips them off to authorities, they are sent on an increasingly erratic journey in search of a place to call their own."}
{"category": "New TV This Week", "movie": "The Witcher", "rating": "83%", "description": "The witcher Geralt, a mutated monster hunter, struggles to find his place in a world in which people often prove more wicked than beasts."}
